### ISSUE TITLE
Any way to detect  index when scrolling (left<->right ) from viewcontroller ? 

### ISSUE THREAD

**Issue by jams032** [yudiz-solutions/SJCenterFlowLayout#1]
Thanks for implementing a nice demo. I was checking the code. i want to detect the current item/index when i scroll cell left to right or right to left. 

After selection/clicking , we can easily detect the current selected item from 

`    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        if self.scrollToEdgeEnabled, let cIndexPath = centerFlowLayout.currentCenteredIndexPath,
            cIndexPath != indexPath {
} } `

Which works fine. 

// scrollToEdgeEnabled: Bool = true // in my code

My question is , when i scroll items(left<->right direction), i don't have any delegate to track which page it is now or which index/item is selected after scroll. I only can detect it from did-select delegate.

How to detect page index/item from viewcontroller easily ? 

Thank you again for the nice demo.

**Comment by isandeepj** [comment]
Hello @jams032 

Here your queries feedback. I hope this helps you. Please let me know if any issue. 
1.  `centerFlowLayout.currentCenteredIndexPath`  to get currently **selected indexpath**
2. `centerFlowLayout.currentCenteredPage` to get **current selected page**

**Comment by jams032** [comment]
@sandeep-yudiz Say, i am in the viewcontroller class now. From where i can called this ? Any place to call it in viewcontroller class when user is scrolling the collectionview ?

**Comment by jams032** [comment]
@sandeep-yudiz, applying the code in viewcontroller,  i got the changed index after scroll finish : 

    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        if let cIndexPath = centerFlowLayout.currentCenteredIndexPath {
            print("\(cIndexPath)")
        }
    }

Do you think this is the only correct way ?

**Comment by isandeepj** [comment]
@jams032 you can do 2 way based on your requirement
1. If you continue to track which current(center) indexPath then use scroll view did scroll delegate method. This method continues to called when you scroll left or right.
```
// any offset changes on called
func scrollViewDidScroll(_ scrollView: UIScrollView) {
        if let indexPath = centerFlowLayout.currentCenteredIndexPath {
            print("Current indexPath: \(indexPath)")
        }
    }
```

2. After scrolling end with left or right then you can use the scroll view did end decelerating delegate method. This method not a continuous called on scrolling left or right.
```
// called when scroll view grinds to a halt
func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        if let indexPath = centerFlowLayout.currentCenteredIndexPath {
            print("Current indexPath: \(indexPath)")
        }
    }
```

**Comment by jams032** [comment]
@sandeep-yudiz yeah, i got it. Thank you so much for nice reply. I prefer using scrollViewDidEndDecelerating method because it is called at the end. scrollViewDidScroll is called so many times while scrolling, so i should not update UI so many times. Another query to you:

In the first load, we just load the collectionview with array elements. It set first item in the center. How i can set another index(may be middle item, index will be array.count/2) manually in the first load. Viewing the items from both sided will look nice in the first on viewcontroller, that's why i want to do it. Any way to set middle item in the first load ? 

Thank you again. 

![Screenshot 2020-11-12 at 8 00 41 AM](https://user-images.githubusercontent.com/13532330/98885938-2a2dde00-24bd-11eb-8967-df417fa9ab26.png)

**Comment by isandeepj** [comment]
@jams032 you can use `scrollToPage(atIndex index: Int, animated: Bool = true) ` method to scroll a specific index.  I hope this helps you. Please let me know if any issue.

```
let index =  array.count/2
collectionView.performBatchUpdates(nil) { [weak self] (isLoded) in
            guard let weakSelf = self, isLoded else { return}
            weakSelf.centerFlowLayout.scrollToPage(atIndex: index, animated: true)
 }
```

**Comment by jams032** [comment]
@sandeep-yudiz , i found this from the implementation. 
You are awesome, thanks for your support.

**Comment by isandeepj** [comment]
@jams032 
Most welcome!

**Comment by jams032** [comment]
@sandeep-yudiz , any shortcut to do this ? Can we show multiple side item ? 

![Screenshot 2020-11-12 at 12 42 26 PM](https://user-images.githubusercontent.com/13532330/98904817-86f0bf00-24e4-11eb-9a8e-ce98ba50d2c0.png)

**Comment by isandeepj** [comment]
@jams032 sorry, not possible with the current code structure for following UI. 

![](https://user-images.githubusercontent.com/13532330/98904817-86f0bf00-24e4-11eb-9a8e-ce98ba50d2c0.png)
.
